### ISSUE TITLE
What does "when I was coming up in dharma" mean?

### ISSUE THREAD

**Issue by carun** [carun/mctb#1]

**Comment by danielmingram** [comment]
Coming up means something like: developing, growing up, progressing, like "when I was coming up in school or my career"

**Comment by carun** [comment]
Thanks @danielmingram. I should've clarified it better.

I wanted to understand what "dharma" means here. In our Tamil culture the word dharma ([dharmam/aram in Tamil](https://en.wiktionary.org/wiki/%E0%AE%85%E0%AE%B1%E0%AE%AE%E0%AF%8D)) means moral or virtue or performance of good works. Is there an interpretation from that angle? I'd like to know if there's an alternative definition of Dharma.

**Comment by carun** [comment]
From https://studybuddhism.com/en/essentials/what-is/what-is-the-dharma, it looks like Dharma in the world of Buddhism means Buddha's teachings. If this is accurate in the context in which the phrase "when I was coming up in Dharma" was used, it could mean, "as I was progressing with the teachings of the Buddha". Is my understanding correct? Once I understand the original meaning, I'll try to match the original English expression in Tamil as close as possible.

**Comment by danielmingram** [comment]
Dhamma also means truth, meaning understanding how things are, Buddha or no, so it could mean “practicing to understand how reality is”.

**Comment by carun** [comment]
Thanks @danielmingram.
