### ISSUE TITLE
What does "chicken-friend detriment" mean?

### ISSUE THREAD

**Issue by carun** [carun/mctb#3]

**Comment by danielmingram** [comment]
"Chicken-fried" is a slightly US Southernized version of "fried", with the addition of "chicken" meant to be a colloquial embellishment that makes it a bit funnier, as in people in the South like fried chicken (as do lots of other people, actually). "Fried" means something similar to "toasted", "burnt", "frazzled", etc.

**Comment by carun** [comment]
Thanks. Glad I got it right in the translation. 🙂
